python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1101.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1102.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1103.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1104.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1108.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1109.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1110.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1201.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1203.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1210.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1213.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1215.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1216.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1217.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1218.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1219.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1220.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1225.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1227.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1229.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1231.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1232.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1233.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1234.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1235.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1236.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1240.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1256.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1258.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1259.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1260.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1262.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1264.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1268.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1269.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1271.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1293.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1301.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1303.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1304.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1305.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1307.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1308.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1309.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1310.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1312.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1313.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1314.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1315.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1316.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1319.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1321.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1323.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1324.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1325.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1326.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1333.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1336.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1337.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1338.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1339.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1340.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1341.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1342.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1343.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1402.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1409.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1410.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1413.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1414.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1416.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1417.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1418.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1419.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1423.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1432.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1434.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1435.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1436.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1437.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1438.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1439.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1440.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1441.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1442.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1443.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1444.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1445.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1446.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1447.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1449.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1451.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1453.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1454.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1455.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1457.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1460.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1463.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1464.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1465.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1466.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1467.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1468.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1469.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1470.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1471.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1472.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1473.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1474.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1475.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1476.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1477.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1503.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1504.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1506.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1512.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1513.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1514.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1515.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1517.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1519.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1521.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1522.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1524.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1525.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1526.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1527.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1528.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1529.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1530.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1531.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1532.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1533.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1535.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1536.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1537.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1538.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1539.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1540.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1541.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1560.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1563.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1566.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1568.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1569.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1570.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1580.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1582.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1583.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1584.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1585.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1586.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1587.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1589.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1590.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1591.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1592.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1593.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1595.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1597.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1598.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1599.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1602.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1603.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1604.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1605.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1608.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1609.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1611.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1612.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1613.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1614.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1615.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1616.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1617.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1618.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1626.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1701.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1704.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1707.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1708.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1711.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1712.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1713.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1715.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1717.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1718.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1720.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1721.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1722.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1723.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1724.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1725.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1726.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1727.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1729.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1730.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1731.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1732.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1733.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1734.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1735.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1736.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1737.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1742.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1752.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1760.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1762.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1773.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1777.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1780.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1781.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1783.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1784.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1785.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1786.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1787.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1788.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1789.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1795.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1796.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1799.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1802.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1805.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1806.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1808.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1809.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1810.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1813.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1815.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1817.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1902.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1903.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1904.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1905.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1906.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1907.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 1909.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 2002.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 2007.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 2008.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 2009.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 2010.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 2012.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 2013.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 2014.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 2020.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 2023.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 2024.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 2025.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 2027.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 2028.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 2029.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 2030.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 2031.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 2032.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 2033.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 2034.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 2035.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 2038.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 2049.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 2059.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 2061.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 2062.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 2063.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 2064.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 2065.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 2066.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 2069.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 2070.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 2071.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 2072.txt
python3 InsertData2DbByFile.py Data\TXT\BzPerformance\ 2073.txt